### ISSUE TITLE
thesis-central and thesis-central-qa are not accessible

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pdc_discovery#413]

**Comment by jrgriffiniii** [comment]
I could not immediately diagnose the errors with these deployments. I am trying to restart the applications currently, but I keep encountering the following:

```bash
[thesiscentralsu@libtc201l Vireo]$ :: loading settings :: url = jar:file:/home/thesiscentralsu/play1-1.3.0/framework/lib/ivy-2.3.0.jar!/org/apache/ivy/core/sett
ings/ivysettings.xml
Exception in thread "main" play.exceptions.DatabaseException: Cannot connected t
o the database[default], Connections could not be acquired from the underlying d
atabase!
        at play.db.DBPlugin.onApplicationStart(DBPlugin.java:196)
        at play.plugins.PluginCollection.onApplicationStart(PluginCollection.jav
a:515)
        at play.Play.start(Play.java:537)
        at play.Play.init(Play.java:309)
        at play.server.Server.main(Server.java:160)
Caused by: java.sql.SQLException: Connections could not be acquired from the und
erlying database!
        at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
        at play.db.DBPlugin.onApplicationStart(DBPlugin.java:179)
        ... 4 more
Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A Resourc
ePool could not acquire a resource from its primary factory or source.
        at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicRes
ourcePool.java:1463)
```

**Comment by jrgriffiniii** [comment]
I truly do not understand why the connection is failing from inside of the application:

```bash
[thesiscentralsu@libtc201l Vireo]$ psql -h theses-central-2020.ct9hnzmkuoct.us-e
ast-1.rds.amazonaws.com -W -U thesis-prod thesis-prod-db
Password for user thesis-prod:
psql (9.6.20, server 12.9)
WARNING: psql major version 9.6, server major version 12.
         Some psql features might not work.
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

thesis-prod-db=> \q
```

**Comment by jrgriffiniii** [comment]
The database URL and credentials are being properly passed to the application here:

https://github.com/playframework/play1/blob/629aee531fd3290113bedff97f7d762646304ed9/framework/pym/play/application.py#L29

I have been checking this within the stack traces, and my fear is that this may be related to an out-of-date Java dependency.
